9tigerio/db2rest

- pom.xml
- src/main/java/com/homihq/db2rest/exception/GlobalExceptionHandler.java
- src/main/java/com/homihq/db2rest/rest/read/ReadController.java
- src/main/java/com/homihq/db2rest/rest/read/ReadService.java
- src/main/java/com/homihq/db2rest/rest/read/model/QueryRequest.java
- src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
Very basic implementation of the endpoint `/query`. Added validation when the field `sql` is empty. Added integration tests as well.
We need to gracefully handle database exceptions. For e.g. when the user does not provide with required parameters in the request, Or, when the SQL statement contains syntax errors etc.
> Api to execute custom query

- src/main/java/com/homihq/db2rest/rest/create/CreateController.java
- src/main/java/com/homihq/db2rest/rest/create/CreateService.java
- src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
- src/test/resources/mysql/mysql-sakila.sql
- src/test/resources/pg/postgres-sakila.sql
added:
1. tsid support for bulk creation
2. tests to test tsid for create
3. tests to test tsid for bulk create
Tests include the following scenarios:
1. tsidType matches with defined type
2. tsidType doesn't match with defined type
3. tsidType not provided (default is used)
> added tsid for bulk creation and tests

- src/main/java/com/homihq/db2rest/rest/delete/DeleteController.java
- src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
- src/main/java/com/homihq/db2rest/rest/delete/dto/DeleteResponse.java
- src/test/java/com/homihq/db2rest/rest/MySQLDeleteControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgProcedureControllerTest.java
- src/test/resources/application-it.yaml
- src/test/resources/mysql/mysql-sakila-data.sql
- src/test/resources/pg/postgres-sakila-data.sql
I did not add integration test for delete all when allow safe delete is false. I'm not sure how to override an application property just for a single test method.
> Integration tests for delete

- src/main/java/com/homihq/db2rest/rest/read/ReadService.java
- src/main/java/com/homihq/db2rest/rest/read/v2/processor/QueryCreatorTemplate.java
> #259 - add limit and offset

- src/main/java/com/homihq/db2rest/dialect/Dialect.java
- src/main/java/com/homihq/db2rest/dialect/MySQLDialect.java
- src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
- src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
- src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
- src/main/java/com/homihq/db2rest/rest/read/processor/RootWhereProcessor.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/EndWithOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/EqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/GreaterThanEqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/GreaterThanOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/InOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/LessThanEqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/LessThanOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/LikeOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/NotEqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/NotInOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/OperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/operator/handler/StartWithOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql2/visitor/BaseRSQLVisitor.java
> #286 - type conversion error

- src/main/java/com/homihq/db2rest/dialect/Dialect.java
- src/main/java/com/homihq/db2rest/rest/delete/dto/DeleteContext.java
- src/main/java/com/homihq/db2rest/rest/update/UpdateController.java
- src/main/java/com/homihq/db2rest/rest/update/UpdateCreatorTemplate.java
- src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
- src/main/java/com/homihq/db2rest/rest/update/dto/UpdateContext.java
- src/main/resources/application.yml
- src/main/resources/sql-templates/update.sql
> #296 - cleanup schema dependency and mybatis for update

- src/main/java/com/homihq/db2rest/jdbc/rest/schema/SchemaController.java
- I felt that the term "condition" is too closely related to that of an "expression", etc. and can be confusing for non-English speakers (when translated).  Where the code we have actually only uses a value, so we should just say it that way.
> Clarify schema filter error message

- Dockerfile
- Adds comment into `./Dockerfile` just in case someone pulls the image and stuck wondering what the hell is the default service port.  (LIKE I DID!!!)
> Add comment about default service port 8080

- api-rest/src/test/java/com/homihq/db2rest/rest/DateTimeUtil.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mongo/MongoDBControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mongo/MongoDBDateTimeAllTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mysql/MySQLDateTimeAllTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/pg/PGDateTimeAllTest.java
- api-rest/src/test/resources/oracle/oracle-sakila.sql
Tested all crud endpoint using timestamps for all databases except Oracle.
1. One test fails on Postgresql timestamp insertion with incorrect DateTime.
Error Type
DateTime parse error.
Reason.
The processing of postgres data insertion is 'parsed by hand' unlike the others which delegate to the Database itself.
This causes a Date parse error for incorrect Datetime which is not handled in the parsing process. Therefore the server crashes and the error is not propagated and sent to the client.
Proposed Solution.
Make the insertion delegate to the db like all other db supports, so that errors will be caught and properly propagated.
> DateTime integration test for all the databases except oracle

- api-rest/src/test/java/com/homihq/db2rest/jdbc/rest/meta/db/DbInfoControllerIntegrationTest.java
- api-rest/src/test/java/com/homihq/db2rest/jdbc/rest/meta/db/DbInfoControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/jdbc/rest/meta/schema/SchemaControllerIntegrationTest.java
- api-rest/src/test/java/com/homihq/db2rest/jdbc/rest/meta/schema/SchemaControllerTest.java
This class is responsible for returning the metadata about the databases connected to the service. Added one test for the getObjects method which returns a list of DbInfoObject.
resolves #715
> Adding Test for DbInfoController and SchemaController  [resolves #715]

- api-rest/src/main/resources/application.yml
- auth/auth-sample.json
- auth/auth-sample.yml
- auth/src/main/java/com/homihq/db2rest/auth/AuthConfiguration.java
- auth/src/main/java/com/homihq/db2rest/auth/AuthFilter.java
- auth/src/main/java/com/homihq/db2rest/auth/apikey/ApiKeyAuthProvider.java
- auth/src/main/java/com/homihq/db2rest/auth/basic/BasicAuthProvider.java
- auth/src/main/java/com/homihq/db2rest/auth/common/AbstractAuthProvider.java
- auth/src/main/java/com/homihq/db2rest/auth/common/ApiKey.java
- auth/src/main/java/com/homihq/db2rest/auth/common/AuthDataProvider.java
- auth/src/main/java/com/homihq/db2rest/auth/common/AuthDataSource.java
- auth/src/main/java/com/homihq/db2rest/auth/data/ApiAuthDataProvider.java
- auth/src/main/java/com/homihq/db2rest/auth/data/FileAuthDataProvider.java
- auth/src/main/java/com/homihq/db2rest/auth/data/NoAuthdataProvider.java
- auth/src/main/java/com/homihq/db2rest/auth/jwt/JwtAuthProvider.java
The issue [712](https://github.com/9tigerio/db2rest/issues/712)
> Support api key auth

- api-rest/pom-oracle9i.xml
- api-rest/pom.xml
- auth/pom.xml
- db2rest-common/pom.xml
- mariadb-dialect/pom.xml
- mongo-support/pom.xml
- mssql-dialect/pom.xml
- mysql-dialect/pom.xml
- oracle-dialect/pom.xml
- oracle9i-dialect/pom.xml
- pg-dialect/pom.xml
- rdbms-common/pom.xml
- rdbms-spring-boot-starter/pom.xml
- rdbms-support/pom.xml
- rest-common/pom.xml
- since we have registered a new namespace within Sonatype's Central, we need to update all the POM's as well, for proper packaging.
> Update new groupId `io.9tiger` in POMs

- .github/workflows/maven-central-publish.yml
- pom.xml
- the problem is the MAVEN_GPG_KEY is not parsed or getting injected correct?  error during Action run https://github.com/9tigerio/db2rest/actions/runs/11639045655/job/32415185526#step:4:825
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.2.7:sign
(sign-artifacts) on project db2rest-parent: Key ring material not found -> [Help 1]
```
Found out in maven-gpg-plugin source code that "key material" actually means `MAVEN_GPG_KEY`.  Thanks source!
- verify is the default, so can remove
> temporarily adding error stack tracing with -e

- api-rest/pom-oracle9i.xml
- needs to be a constant, NOT an expression like ${project.parent.version}
> fix version string on oracle9i POM

- api-rest/src/main/java/com/homihq/db2rest/jdbc/rest/meta/schema/ColumnObject.java
- api-rest/src/main/java/com/homihq/db2rest/jdbc/rest/meta/schema/SchemaController.java
- api-rest/src/main/java/com/homihq/db2rest/jdbc/rest/meta/schema/SchemaRestApi.java
- api-rest/src/main/java/com/homihq/db2rest/jdbc/rest/meta/schema/TableObject.java
- api-rest/src/main/java/com/homihq/db2rest/jdbc/rest/meta/schema/TableWithColumnsObject.java
- api-rest/src/test/java/com/homihq/db2rest/jdbc/rest/meta/schema/SchemaControllerIntegrationTest.java
- api-rest/src/test/java/com/homihq/db2rest/jdbc/rest/meta/schema/SchemaControllerTest.java
Before:
```json
{
"schema": "public",
"name": "django_migrations",
"type": "TABLE"
}
```
After:
```json
{
"schema": "public",
"name": "django_migrations",
"type": "TABLE",
"columns": [
{
"name": "id",
"pk": true,
"dataType": "int4"
},
{
"name": "app",
"pk": false,
"dataType": "varchar"
},
{
"name": "name",
"pk": false,
"dataType": "varchar"
},
{
"name": "applied",
"pk": false,
"dataType": "timestamptz"
}
]
}
```
> Add column information to database schema endpoint

- api-rest/src/test/java/com/homihq/db2rest/rest/oracle/OracleProcedureControllerTest.java
- api-rest/src/test/resources/oracle/oracle-sakila.sql
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/core/service/JdbcProcedureService.java
Oracle stored procedure call returns result.
> Fix oracle db stored procedure call

- mariadb-dialect/src/main/java/com/homihq/db2rest/jdbc/config/dialect/MariaDBDialect.java
- mssql-dialect/src/main/java/com/homihq/db2rest/jdbc/config/dialect/MsSQLServerDialect.java
- mysql-dialect/src/main/java/com/homihq/db2rest/jdbc/config/dialect/MySQLDialect.java
- oracle-dialect/src/main/java/com/homihq/db2rest/jdbc/config/dialect/OracleDialect.java
- oracle9i-dialect/src/main/java/com/homihq/db2rest/jdbc/config/dialect/OracleDialect.java
- pg-dialect/src/main/java/com/homihq/db2rest/jdbc/config/dialect/PostGreSQLDialect.java
- rdbms-common/src/main/java/com/homihq/db2rest/jdbc/config/dialect/Dialect.java
Also pulled up common variables within each subclass to ensure that all subclasses have common functionality.
I'm not sure if there will be any future subclasses for Dialect, but this refactor will ensure they have the same features.
> refactor(dialect): converted Dialect from an interface into an abstract class

- pg-dialect/src/main/java/com/homihq/db2rest/jdbc/config/driver/PgSingleCertValidatingFactory.java
This is done with the intent of improving readability of the PgSingleCertValidatingFactory method.
> Separated nested try/catch blocks into their own methods 

- db2rest-common/src/main/java/com/homihq/db2rest/core/exception/InvalidColumnException.java
- Because this is prefixed in the "detail" field output with "Failed to parse RQL - " then saying "missing" makes it seem like RQL had some problem parsing, when in fact, RQL had no problem at all, it was the DB that could not find a column.  It's better to say "not found" instead of "missing".
> Clarify messaging for column not found

- dialects/mariadb-dialect/src/main/java/com/homihq/db2rest/jdbc/config/dialect/MariaDBDialect.java
- dialects/mysql-dialect/src/main/java/com/homihq/db2rest/jdbc/config/dialect/MySQLDialect.java
- dialects/pg-dialect/src/main/java/com/homihq/db2rest/jdbc/config/dialect/PostGreSQLDialect.java
- rdbms-common/src/main/java/com/homihq/db2rest/jdbc/config/dialect/Dialect.java
TIMESTAMP handling in MySQL, MariaDB and PostgreSQL was not correct.
Those columns expect LocalDateTime and not OffsetDateTime
> #760 - Fixing Dialects for TIMESTAMP columns

- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/util/AliasGenerator.java
Intends to fix #850 
We get the last 12 chars from a UUIDv4 to add a lot more randomness to the table alias generation.
With 1-1000 int range a collision is much more likely to happen leading to two different tables having the same alias which results in a SQL syntax error
> fix(rdbms-support) Replace int with UUID for table aliasing

- api-rest/src/main/java/com/homihq/db2rest/config/WebMvcConfiguration.java
- api-rest/src/main/resources/application.yml
- rest-common/src/main/java/com/homihq/db2rest/config/CorsConfig.java
- rest-common/src/main/java/com/homihq/db2rest/config/Db2RestConfigProperties.java
REF https://github.com/9tigerio/db2rest/issues/859
This PR adds global CORS configuration to allow requests from specified origins, headers, and methods, with configurable values
- Implemented `CorsConfig` class to read CORS settings from `application.yml`, allowing overrides via environment variables (`CORS_ORIGIN_URL`, `CORS_HEADERS_ALLOWED`, `CORS_METHODS_ALLOWED`).  
- Updated `WebMvcConfiguration` to apply global CORS rules using values from `CorsConfig`.  
- Ensured default values (`*`) are used if environment variables are not set.  
CORS settings can now be modified at runtime by passing environment variables:  
```bash
java -jar db2rest.jar --CORS_ORIGIN_URL='http://localhost:9000' --CORS_HEADERS_ALLOWED='*' --CORS_METHODS_ALLOWED='GET,POST'
```
- Review if additional security …
> Add Global CORS Configuration with Externalized Properties #859

- rdbms-common/src/main/java/com/homihq/db2rest/jdbc/config/dialect/Dialect.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/processor/RootWhereProcessor.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/EqualToOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/GreaterThanEqualToOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/GreaterThanOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/InOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/JsonContainOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/JsonbContainOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/JsonbEqualToOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/LessThanEqualToOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/LessThanOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/NotEqualToOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/NotInOperatorHandler.java
When we pass a UUID as a String object to Spring JDBC it is not able to query the postgres database properly leading to issues. 
Similar StackOverflow articles: https://stackoverflow.com/questions/55286397/how-to-compare-character-varying-varcar-to-uuid-in-postgresql
The solution is to cast the object to a valid UUID object and then send to Spring JDBC to query. 
Fixes #880
> Fix(api-rest): Fix for UUID not getting properly sent to postgres. Fixes #880
