- pom.xml
- src/main/java/com/homihq/db2rest/rest/handler/SelectColumnBuilder.java
- src/main/java/com/homihq/db2rest/rest/resource/QueryResource.java
- src/main/java/com/homihq/db2rest/rest/service/QueryService.java
- src/main/java/com/homihq/db2rest/rsql/FilterBuilderService.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/jooq/JooqRSQLOperatorHandlers.java
- src/main/java/com/homihq/db2rest/rsql/parser/JOOQRSQLVisitor.java
> finished on #16

- README.md
- src/main/java/com/homihq/db2rest/rest/service/QueryService.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/jooq/JooqEqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/jooq/JooqGreaterThanOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/jooq/JooqRSQLOperatorHandlers.java
> working on #21

- README.md
- src/main/java/com/homihq/db2rest/rest/service/QueryService.java
- src/main/java/com/homihq/db2rest/rsql/FilterBuilderService.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/EqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/GreaterThanEqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/GreaterThanOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/jooq/JooqGreaterThanEqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/jooq/JooqRSQLOperatorHandlers.java
> working on #23

- README.md
- src/main/java/com/homihq/db2rest/rsql/operators/handler/LessThanEqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/jooq/JooqLessThanEqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/jooq/JooqRSQLOperatorHandlers.java
> working #27

- README.md
- src/main/java/com/homihq/db2rest/rsql/operators/handler/NotEqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/jooq/JooqNotEqualToOperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/jooq/JooqRSQLOperatorHandlers.java
> working #29

- pom.xml
- src/main/java/com/homihq/db2rest/rest/query/QueryResource.java
- src/main/java/com/homihq/db2rest/rest/query/QueryService.java
- src/main/java/com/homihq/db2rest/rest/query/model/JoinTable.java
- src/main/java/com/homihq/db2rest/schema/SchemaService.java
In the early release, no nested multi-table joins are supported.
> #52 - covers single join table with changed DSL syntax. only inner join supported.

- src/main/java/com/homihq/db2rest/rest/query/helper/SelectBuilder.java
> #43 - join table columns added to select, * not supported.

- README.md
- pom.xml
> #64 - updated documentation for installation.

- README.md
> #61 - tested inserts with mysql, updated doc

- README.md
- src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
- src/main/java/com/homihq/db2rest/rsql/operators/OperatorHandler.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/EqualToOperatorHandler.java
> #62 - update support bug fix and doc added

- src/main/java/com/homihq/db2rest/rest/delete/DeleteController.java
- src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
> #87 - remove jooq from delete

- src/test/java/com/homihq/db2rest/BaseIntegrationTest.java
> #108 - restdocs now configured to generate markdown

- .github/workflows/ci-build.yml
> #109 - testing github action for integration tests and build

- src/main/java/com/homihq/db2rest/mybatis/DB2RestRenderingStrategy.java
- src/main/java/com/homihq/db2rest/rest/create/CreateController.java
- src/main/java/com/homihq/db2rest/rest/create/CreateService.java
- src/main/java/com/homihq/db2rest/rest/create/dto/CreateBulkResponse.java
- src/main/java/com/homihq/db2rest/rest/create/dto/CreateResponse.java
- src/main/resources/application.yml
> #98 - update based on tests

- src/test/java/com/homihq/db2rest/BaseIntegrationTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
Added test for MySQL READ controller
> adding integration test support with Test container for MySQL

- src/main/java/com/homihq/db2rest/exception/RpcException.java
- src/main/java/com/homihq/db2rest/rest/rpc/FunctionController.java
- src/main/java/com/homihq/db2rest/rest/rpc/ProcedureController.java
- src/main/java/com/homihq/db2rest/rest/rpc/SubRoutine.java
Exception handling for procedure and function calls
> Exception handling for procedure and function calls

- src/main/java/com/homihq/db2rest/exception/InvalidColumnException.java
- src/main/java/com/homihq/db2rest/exception/InvalidSchemaException.java
- src/main/java/com/homihq/db2rest/exception/InvalidTableException.java
- src/main/java/com/homihq/db2rest/exception/RpcException.java
Remove redundant setDetail() on the ProblemDetail object
> Remove redundant setDetail

- src/main/java/com/homihq/db2rest/exception/GenericDataAccessException.java
- src/main/java/com/homihq/db2rest/rest/create/CreateService.java
- src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
> #116 - integration test added for postgresql insert error.

- README.md
> #76 - docker documentation added.

- README.md
- fix typos
- clarify "no code generation" which really means "does not use code generation"
> Fix typos and add clarity to README

- src/test/java/com/homihq/db2rest/rest/MySQLCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
> #136 - ading integration test for bulk insert for postgresql

- src/test/java/com/homihq/db2rest/MySQLBaseIntegrationTest.java
- src/test/java/com/homihq/db2rest/PostgreSQLBaseIntegrationTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
> #135 - mysql bulk insert, minor other fixes

- pom.xml
- src/main/java/com/homihq/db2rest/rest/create/CreateController.java
- src/main/java/com/homihq/db2rest/rest/create/CreateService.java
> added tsid column check and add autogenerated tsid

- pom.xml
- src/main/java/com/homihq/db2rest/rest/create/BulkCreateController.java
- src/main/java/com/homihq/db2rest/rest/create/CreateController.java
- src/main/java/com/homihq/db2rest/rest/create/bulk/CSVDataProcessor.java
- src/main/java/com/homihq/db2rest/rest/create/bulk/DataProcessor.java
- src/main/java/com/homihq/db2rest/rest/create/bulk/JSONDataProcessor.java
- src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
> #151 - csv bulk upload added.

- src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
simple change to fix url in tests
> fixed tests

- src/main/java/com/homihq/db2rest/rest/read/helper/ReadContext.java
- src/main/java/com/homihq/db2rest/rest/read/helper/SortBuilder.java
- src/main/java/com/homihq/db2rest/rest/read/helper/TableUtil.java
- src/main/java/com/homihq/db2rest/rest/read/model/DbAlias.java
- src/main/java/com/homihq/db2rest/rest/read/model/DbColumn.java
- src/main/java/com/homihq/db2rest/rest/read/model/DbTable.java
> fix #162 - fix sort issue

- src/main/java/com/homihq/db2rest/mybatis/MyBatisTable.java
- src/main/java/com/homihq/db2rest/rest/read/helper/JoinBuilder.java
- src/main/java/com/homihq/db2rest/rest/read/helper/ProjectionBuilder.java
- src/main/java/com/homihq/db2rest/rest/read/helper/ReadContext.java
- src/main/java/com/homihq/db2rest/rest/read/helper/SelectBuilder.java
- src/main/java/com/homihq/db2rest/schema/SchemaManager.java
> #169 - resolving multi join.

- src/test/java/com/homihq/db2rest/rest/MySQLDeleteAllTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLDeleteControllerTest.java
- src/test/resources/mysql/mysql-sakila-data.sql
- src/test/resources/mysql/mysql-sakila.sql
- src/test/resources/pg/postgres-sakila-data.sql
- src/test/resources/pg/postgres-sakila.sql
Created a simple `country` table which contains test data for delete all operation only
> integration test for delete all when allow safe delete is false

- src/main/java/com/homihq/db2rest/config/Db2RestConfigProperties.java
- src/main/java/com/homihq/db2rest/config/MultiTenancy.java
- src/main/java/com/homihq/db2rest/rest/delete/DeleteController.java
- src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
- src/main/java/com/homihq/db2rest/schema/SchemaManager.java
- src/test/java/com/homihq/db2rest/rest/MySQLDeleteAllTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLDeleteControllerTest.java
> fix tests due to change of http status for delete success to 204

- pom.xml
- src/main/java/com/homihq/db2rest/jdbc/JdbcDataTypeConverter.java
- src/main/java/com/homihq/db2rest/mybatis/MyBatisTable.java
- src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
- src/main/java/com/homihq/db2rest/rsql/operators/Operator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/EndWithOperator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/EqualToOperator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/GreaterThanEqualToOperator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/GreaterThanOperator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/InOperator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/LessThanEqualToOperator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/LessThanOperator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/LikeOperator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/NotEqualToOperator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/NotInOperator.java
- src/main/java/com/homihq/db2rest/rsql/operators/handler/StartWithOperator.java
- src/main/java/com/homihq/db2rest/rsql/parser/MyBatisFilterVisitor.java
- src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLDeleteControllerTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLFunctionControllerTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLProcedureControllerTest.java
- src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgFunctionControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgProcedureControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
> #197 - fix integer type

- pom.xml
> #200 - upgrade to spring boot 3.2.2

- src/main/java/com/homihq/db2rest/rest/create/CreateController.java
- src/main/java/com/homihq/db2rest/rest/create/CreateRestApi.java
> #213 - refactored create controller

- src/main/java/com/homihq/db2rest/rest/create/BulkCreateApi.java
- src/main/java/com/homihq/db2rest/rest/create/BulkCreateController.java
> #215 - refactored bulk create controller

- src/main/java/com/homihq/db2rest/mybatis/MyBatisTable.java
- src/main/java/com/homihq/db2rest/rest/read/helper/ReadContext.java
- src/main/java/com/homihq/db2rest/rest/read/helper/SelectBuilder.java
> #224 - fixed now if select is not specified all columns of the root table is returned.

- src/main/java/com/homihq/db2rest/rest/create/BulkCreateRestApi.java
- src/main/java/com/homihq/db2rest/rest/create/BulkCreateRestController.java
- src/main/java/com/homihq/db2rest/rest/delete/DeleteController.java
- src/main/java/com/homihq/db2rest/rest/delete/DeleteRestApi.java
> #220 - refactor delete controller

- src/main/java/com/homihq/db2rest/rest/read/CustomQueryController.java
- src/main/java/com/homihq/db2rest/rest/read/CustomQueryService.java
- src/main/java/com/homihq/db2rest/rest/read/ReadController.java
- src/main/java/com/homihq/db2rest/rest/read/ReadService.java
> #251 moved custom query to separate class - SRP principle

- src/main/java/com/homihq/db2rest/rest/read/FindOneController.java
- src/main/java/com/homihq/db2rest/rest/read/FindOneService.java
- src/main/java/com/homihq/db2rest/rest/read/ReadController.java
> #254 refactor find one query

- src/main/java/com/homihq/db2rest/rest/read/processor/QueryCreatorTemplate.java
- src/main/resources/application.yml
- src/main/resources/sql-templates/read.sql
> #275 - support for pagination

- src/main/java/com/homihq/db2rest/model/DbSort.java
- src/main/java/com/homihq/db2rest/rest/read/ReadController.java
- src/main/java/com/homihq/db2rest/rest/read/ReadService.java
- src/main/java/com/homihq/db2rest/rest/read/dto/ReadContext.java
- src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
- src/main/java/com/homihq/db2rest/rest/read/processor/OrderByProcessor.java
- src/main/java/com/homihq/db2rest/rest/read/processor/QueryCreatorTemplate.java
- src/main/java/com/homihq/db2rest/rest/read/processor/ReadProcessor.java
- src/main/java/com/homihq/db2rest/rest/read/processor/RootTableFieldProcessor.java
- src/main/java/com/homihq/db2rest/rest/read/processor/RootTableProcessor.java
- src/main/java/com/homihq/db2rest/rest/read/processor/RootWhereProcessor.java
- src/main/resources/sql-templates/read.sql
> #261 - sort processing

- design/insert.md
> #282 - updated tsid design doc

- src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
> #227 - support timestamp for mysql and postgresql

- src/main/java/com/homihq/db2rest/dialect/MySQLDialect.java
> #216 - support json column support

- src/main/java/com/homihq/db2rest/dialect/Dialect.java
- src/main/java/com/homihq/db2rest/dialect/MySQLDialect.java
- src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
> #202 - mysql view support

- src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
> #232 - timestampz support

- src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
> #231 - timetz support

- README.md
- src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
- src/main/java/com/homihq/db2rest/rest/create/tsid/TSIDProcessor.java
> bulk insert columns support

- pom.xml
- src/main/java/com/homihq/db2rest/Db2restApplication.java
- src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
- src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
- src/main/java/com/homihq/db2rest/rest/create/bulk/CSVDataProcessor.java
- src/main/java/com/homihq/db2rest/rest/create/bulk/JSONDataProcessor.java
- src/main/java/com/homihq/db2rest/rest/read/helper/AliasGenerator.java
> #272 - fix bulk upload

- src/main/java/com/homihq/db2rest/schema/AliasGenerator.java
- src/main/java/com/homihq/db2rest/schema/SchemaManager.java
> #206 - added support for materialized view for postgresql

- src/main/java/com/homihq/db2rest/model/DbTable.java
- src/main/java/com/homihq/db2rest/rest/create/CreateService.java
- src/main/java/com/homihq/db2rest/schema/SchemaManager.java
> #304 - fix pg sql insert keys issue.

- src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
- src/main/java/com/homihq/db2rest/exception/GlobalExceptionHandler.java
- src/main/java/com/homihq/db2rest/rest/create/CreateService.java
> #306 - fix save error response

- src/main/java/com/homihq/db2rest/exception/InvalidColumnException.java
- src/main/java/com/homihq/db2rest/exception/InvalidTableException.java
- src/main/java/com/homihq/db2rest/schema/SchemaManager.java
> #308 - improve error reporting

- pom.xml
- src/main/java/com/homihq/db2rest/rest/create/BulkCreateController.java
- src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
- src/main/java/com/homihq/db2rest/rest/create/CreateService.java
> #316 - remove spring data

- src/main/java/com/homihq/db2rest/auth/unkey/UnKeyAuthFilter.java
> #316 - fix unkey imports

- src/main/java/com/homihq/db2rest/core/model/DbColumn.java
- src/main/java/com/homihq/db2rest/core/model/DbTable.java
- src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
- src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
> #334 - fix column alias handling

- pom.xml
- src/main/java/com/homihq/db2rest/auth/jwt/JwtAuthConfiguration.java
- src/main/java/com/homihq/db2rest/auth/jwt/JwtAuthFilter.java
- src/main/java/com/homihq/db2rest/auth/jwt/service/JwtAuthService.java
- src/main/resources/application.yml
- src/test/java/com/homihq/db2rest/auth/JwtAuthServiceTest.java
> added jwt token verification service

- pom.xml
- src/main/resources/application.yml
- src/main/resources/banner.txt
#354 - Added new banner changes
> Banner Changes

- pom.xml
- src/main/java/com/homihq/db2rest/jdbc/service/JdbcCustomQueryService.java
- src/main/java/com/homihq/db2rest/rest/RestApiConfiguration.java
- src/main/resources/application.yml
> #367 - fix to jar running issues from command line -

- src/main/java/com/homihq/db2rest/core/config/DataSource.java
- src/main/java/com/homihq/db2rest/core/config/Db2RestConfigProperties.java
- src/main/java/com/homihq/db2rest/core/model/DbTable.java
- src/main/java/com/homihq/db2rest/jdbc/JdbcSchemaCache.java
- src/main/java/com/homihq/db2rest/jdbc/config/JdbcSchemaCacheConfiguration.java
- src/main/java/com/homihq/db2rest/jdbc/processor/JoinProcessor.java
- src/main/java/com/homihq/db2rest/jdbc/processor/RootTableProcessor.java
- src/main/java/com/homihq/db2rest/jdbc/sql/DbMeta.java
- src/main/java/com/homihq/db2rest/jdbc/sql/JdbcMetaDataProvider.java
- src/main/java/com/homihq/db2rest/jdbc/sql/JdbcTypeJavaClassMappings.java
- src/main/java/com/homihq/db2rest/jdbc/sql/SqlTypes.java
- src/main/resources/application.yml
> #378 - revised metadata crawler

- pom.xml
- src/main/java/com/homihq/db2rest/jdbc/JdbcSchemaCache.java
- src/main/java/com/homihq/db2rest/jdbc/dialect/PostGreSQLDialect.java
> #394 - removed schemacrawler dependencies

- src/test/java/com/homihq/db2rest/rest/oracle/OracleInnerJoinControllerTest.java
- src/test/resources/oracle/oracle-sakila-data.sql
- src/test/resources/oracle/oracle-sakila.sql
- src/test/resources/testdata/INNER_JOIN_ORACLE.json
> #410 - inner join oracle

- src/test/java/com/homihq/db2rest/rest/mysql/MySQLInnerJoinControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mysql/MySQLInnerJoinMultiTableControllerTest.java
- src/test/java/com/homihq/db2rest/rest/oracle/OracleInnerJoinMultiTableControllerTest.java
- src/test/resources/oracle/oracle-sakila-data.sql
- src/test/resources/oracle/oracle-sakila.sql
- src/test/resources/testdata/INNER_JOIN_MULTI_TABLE_ORACLE.json
> #412 - inner join with multiple tables

- src/test/java/com/homihq/db2rest/rest/oracle/OracleReadControllerTest.java
> #422 - read integration test for oracle

- src/test/java/com/homihq/db2rest/rest/mysql/MySQLReadControllerTest.java
- src/test/java/com/homihq/db2rest/rest/oracle/OracleBulkCreateControllerTest.java
> #397 - bulk create oracle

- pom-oracle9i.xml
- pom.xml
> #425 - oracle9i release

- pom.xml
- src/main/java/com/homihq/db2rest/core/DbOperationService.java
- src/main/java/com/homihq/db2rest/jdbc/config/JdbcCacheConfiguration.java
- src/main/java/com/homihq/db2rest/jdbc/config/JdbcProcessorConfiguration.java
- src/main/java/com/homihq/db2rest/jdbc/config/JdbcServiceConfiguration.java
- src/main/java/com/homihq/db2rest/mongodb/DefaultMongodbOperationService.java
- src/main/java/com/homihq/db2rest/mongodb/MongodbDialect.java
- src/main/java/com/homihq/db2rest/mongodb/MongodbOperationService.java
- src/main/java/com/homihq/db2rest/mongodb/config/MongodbConfiguration.java
- src/main/java/com/homihq/db2rest/mongodb/config/MongodbServiceConfiguration.java
- src/main/java/com/homihq/db2rest/mongodb/service/MongodbCreateService.java
- src/main/resources/application.yml
> mongodb create simple document - work in progress

- src/main/java/com/homihq/db2rest/core/config/DateTimeConfigProperties.java
- src/main/java/com/homihq/db2rest/core/config/DateTimeConfiguration.java
- src/main/resources/application.yml
> #448 - change environment variable name

- src/main/java/com/homihq/db2rest/jdbc/sql/JdbcMetaDataProvider.java
- src/main/java/com/homihq/db2rest/jdbc/sql/MetaDataExtraction.java
- src/main/java/com/homihq/db2rest/jdbc/sql/MetaDataTable.java
- src/main/java/com/homihq/db2rest/jdbc/sql/MySQLDataExtraction.java
- src/main/java/com/homihq/db2rest/jdbc/sql/OracleMetaDataExtraction.java
- src/main/java/com/homihq/db2rest/jdbc/sql/PostgreSQLDataExclusion.java
- src/main/java/com/homihq/db2rest/jdbc/sql/SqlCreatorTemplate.java
- src/main/resources/application.yml
#450 - speed up meta data loading.
> #450 - improve meta data extraction

- src/main/java/com/homihq/db2rest/mongo/config/MongoConfiguration.java
- src/main/java/com/homihq/db2rest/mongo/repository/MongoRepository.java
- src/main/java/com/homihq/db2rest/mongo/rest/MongoController.java
- src/main/java/com/homihq/db2rest/mongo/rest/api/MongoRestApi.java
- src/main/java/com/homihq/db2rest/mongo/rsql/RsqlMongodbAdapter.java
- src/main/java/com/homihq/db2rest/mongo/rsql/argconverters/EntityFieldTypeConverter.java
- src/main/java/com/homihq/db2rest/mongo/rsql/argconverters/FieldSpecificConverter.java
- src/main/java/com/homihq/db2rest/mongo/rsql/argconverters/NoOpConverter.java
- src/main/java/com/homihq/db2rest/mongo/rsql/argconverters/OperatorSpecificConverter.java
- src/main/java/com/homihq/db2rest/mongo/rsql/argconverters/StringToQueryValueConverter.java
- src/main/java/com/homihq/db2rest/mongo/rsql/operator/Operator.java
- src/main/java/com/homihq/db2rest/mongo/rsql/structs/ConversionInfo.java
- src/main/java/com/homihq/db2rest/mongo/rsql/structs/Lazy.java
- src/main/java/com/homihq/db2rest/mongo/rsql/visitor/ComparisonToCriteriaConverter.java
- src/main/java/com/homihq/db2rest/mongo/rsql/visitor/CriteriaBuildingVisitor.java
- src/main/java/com/homihq/db2rest/mongo/utils/LazyUtils.java
This includes rsql integration, filter, sorting and pagination
> mongodb findAll documents

- src/main/java/com/homihq/db2rest/mongo/repository/MongoRepository.java
- src/main/java/com/homihq/db2rest/mongo/rest/MongoController.java
- src/main/java/com/homihq/db2rest/mongo/rest/api/MongoRestApi.java
> Introducing findOne

- src/test/java/com/homihq/db2rest/rest/mysql/MySQLFunctionControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mysql/MySQLProcedureControllerTest.java
- src/test/java/com/homihq/db2rest/rest/pg/PgBasicJoinControllerTest.java
- src/test/java/com/homihq/db2rest/rest/pg/PgCrossJoinControllerTest.java
- src/test/java/com/homihq/db2rest/rest/pg/PgDeleteControllerTest.java
- src/test/java/com/homihq/db2rest/rest/pg/PgFunctionControllerTest.java
- src/test/java/com/homihq/db2rest/rest/pg/PgProcedureControllerTest.java
- src/test/java/com/homihq/db2rest/rest/pg/PgReadControllerTest.java
- src/test/java/com/homihq/db2rest/rest/pg/PgUpdateControllerTest.java
- src/test/resources/pg/postgres-sakila-data.sql
- src/test/resources/pg/postgres-sakila.sql
- src/test/resources/testdata/CROSS_JOIN_TOPS_PG.json
- src/test/resources/testdata/CROSS_JOIN_USERS_PG.json
> #345 - postgresql join integration tests.

- src/main/java/com/homihq/db2rest/d1/D1SchemaCache.java
- src/main/java/com/homihq/db2rest/jdbc/core/model/DbColumn.java
- src/main/java/com/homihq/db2rest/jdbc/core/model/DbTable.java
- src/main/java/com/homihq/db2rest/jdbc/core/service/JdbcReadService.java
- src/main/java/com/homihq/db2rest/jdbc/sql/MySQLDataExtraction.java
- src/main/java/com/homihq/db2rest/jdbc/sql/OracleMetaDataExtraction.java
- src/main/java/com/homihq/db2rest/jdbc/sql/PostgreSQLDataExclusion.java
worked on #489 
Will be available in 0.3.0
> #489 - fix column naming issues

- pom-oracle9i.xml
- pom.xml
- src/main/java/com/homihq/db2rest/jdbc/driver/PgSingleCertValidatingFactory.java
> #494 : new ssl factory class added.

- pom.xml
- src/main/java/com/homihq/db2rest/jdbc/JdbcSchemaCache.java
- src/main/java/com/homihq/db2rest/jdbc/dialect/MariaDBDialect.java
- src/main/java/com/homihq/db2rest/jdbc/sql/JdbcMetaDataProvider.java
- src/main/java/com/homihq/db2rest/jdbc/sql/MariaDBDataExtraction.java
- src/test/java/com/homihq/db2rest/MariaDBBaseIntegrationTest.java
- src/test/java/com/homihq/db2rest/MariaDBContainerConfiguration.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBBasicJoinControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBBulkCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBCountControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBCreateControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBCrossJoinControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBDeleteAllTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBDeleteControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBFunctionControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBInnerJoinControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBInnerJoinMultiTableControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBInnerSelfJoinControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBProcedureControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBReadControllerTest.java
- src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBUpdateControllerTest.java
- src/test/resources/application-it-mariadb.yaml
- src/test/resources/mariadb/mariadb-sakila-data.sql
- src/test/resources/mariadb/mariadb-sakila.sql
#175 - Added integration tests for MariaDB.
> 175 support maria db

- pom.xml
- This "slightly" helps a bit with SEO and Linked Data
- It also helps us get into AI responses a bit faster :-)
> Add project organization metadata into parent pom

- api-rest/src/main/java/com/homihq/db2rest/mongo/rest/MongoController.java
- api-rest/src/main/java/com/homihq/db2rest/mongo/rest/api/MongoRestApi.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mongo/MongoDBControllerTest.java
- mongo-support/src/main/java/com/homihq/db2test/mongo/repository/MongoRepository.java
https://github.com/kdhrubo/db2rest/issues/542
> Mongodb exists endpoint

- api-rest/src/main/java/com/homihq/db2rest/mongo/rest/MongoController.java
- api-rest/src/main/java/com/homihq/db2rest/mongo/rest/api/MongoRestApi.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mongo/MongoDBControllerTest.java
- api-rest/src/test/resources/testdata/BULK_CREATE_ACTOR_REQUEST.json
- mongo-support/src/main/java/com/homihq/db2test/mongo/repository/MongoRepository.java
https://github.com/kdhrubo/db2rest/issues/548
> #548 Mongodb bulk insert

- api-rest/pom-oracle9i.xml
- api-rest/pom.xml
- auth/pom.xml
- db2rest-common/pom.xml
- mariadb-dialect/pom.xml
- mongo-support/pom.xml
- mysql-dialect/pom.xml
- oracle-dialect/pom.xml
- oracle9i-dialect/pom.xml
- pg-dialect/pom.xml
- pg-dialect/src/main/java/com/homihq/db2rest/jdbc/config/dialect/PostGreSQLDialect.java
- pom.xml
- rdbms-common/pom.xml
- rdbms-common/src/main/java/com/homihq/db2rest/jdbc/config/dialect/Dialect.java
- rdbms-spring-boot-starter/pom.xml
- rdbms-support/pom.xml
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/core/SimpleRowMapper.java
- rest-common/pom.xml
> #594 - fix jsonb insert

- api-rest/pom-oracle9i.xml
- api-rest/pom.xml
- api-rest/src/test/resources/testdata/CROSS_JOIN_TOPS_ORACLE.json
- api-rest/src/test/resources/testdata/CROSS_JOIN_TOPS_PG.json
- api-rest/src/test/resources/testdata/CROSS_JOIN_USERS_ORACLE.json
- api-rest/src/test/resources/testdata/CROSS_JOIN_USERS_PG.json
- api-rest/src/test/resources/testdata/LEFT_JOIN.json
- api-rest/src/test/resources/testdata/LEFT_JOIN_ORACLE.json
- api-rest/src/test/resources/testdata/RIGHT_JOIN.json
- api-rest/src/test/resources/testdata/RIGHT_JOIN_ORACLE.json
- auth/pom.xml
- db2rest-common/pom.xml
- mariadb-dialect/pom.xml
- mongo-support/pom.xml
- mysql-dialect/pom.xml
- oracle-dialect/pom.xml
- oracle9i-dialect/pom.xml
- pg-dialect/pom.xml
- pom.xml
- rdbms-common/pom.xml
- rdbms-spring-boot-starter/pom.xml
- rdbms-support/pom.xml
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/dto/JoinDetail.java
- rest-common/pom.xml
> #603 change join type to joinType

- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/CustomRSQLOperators.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/NotLikeOperatorHandler.java
- rdbms-support/src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/RSQLOperatorHandlers.java
> #590 not like operator added

- api-rest/src/main/resources/application.yml
> #243 - gzip configuration

- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLBasicJoinControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLBulkCreateControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLCountControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLCreateControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLCrossJoinControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLDeleteControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLDeleteWithNotAllowedSafeDeleteControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLExistsControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLFindOneControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLFunctionControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLInnerJoinControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLInnerJoinMultiTableControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLInnerSelfJoinControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLProcedureControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLReadControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLUpdateControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mysql/CountTwoTablesSameNameDiffSchemaTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mysql/CreateTwoTablesSameNameDiffSchemaTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mysql/DeleteTwoTablesSameNameDiffSchemaTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mysql/ReadTwoTablesSameNameDiffSchemaTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mysql/UpdateTwoTablesSameNameDiffSchemaTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/oracle/OracleDateTimeAllTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/pg/PgCrossJoinControllerTest.java
#696 - https://github.com/9tigerio/db2rest/issues/696
#697 - https://github.com/9tigerio/db2rest/issues/697
#698 - https://github.com/9tigerio/db2rest/issues/698
#699 - https://github.com/9tigerio/db2rest/issues/699
> Reordered some of the test, executed and they passed. Reviewed for correctness of output data.

- api-rest/src/main/java/com/homihq/db2rest/jdbc/rest/meta/schema/SchemaController.java
> Add clarifying Javadocs to SchemaController

- .github/workflows/maven-central-publish.yml
- .gitignore
- api-rest/pom-oracle9i.xml
- api-rest/pom.xml
- auth/pom.xml
- db2rest-common/pom.xml
- mariadb-dialect/pom.xml
- mongo-support/pom.xml
- mssql-dialect/pom.xml
- mysql-dialect/pom.xml
- oracle-dialect/pom.xml
- oracle9i-dialect/pom.xml
- pg-dialect/pom.xml
- pom.xml
- rdbms-common/pom.xml
- rdbms-spring-boot-starter/pom.xml
- rdbms-support/pom.xml
- rest-common/pom.xml
DONE:
- published GPG key to keyserver.ubuntu.com
TODO:
- setup GPG keys on GitHub Settings
- also ensure local dryrun of release:prepare works on local desktop (not GitHub) and target files are generated correctly
> more publishing fixes

- api-rest/src/main/resources/application.yml
- escapes logging level keys that use special chars `.` , need to wrap with '[ ]'
- fix missing $ for variable
> fix issues within application.yml file

- .github/workflows/maven-central-publish.yml
and we have to do this through setup-java action
> central plugin needs settings.xml populated and

- .github/workflows/snapshot.yml
- README.md
- api-rest/pom-oracle9i.xml
- api-rest/pom.xml
- auth/pom.xml
- db2rest-common/pom.xml
- mariadb-dialect/pom.xml
- mongo-support/pom.xml
- mssql-dialect/pom.xml
- mysql-dialect/pom.xml
- oracle-dialect/pom.xml
- oracle9i-dialect/pom.xml
- pg-dialect/pom.xml
- pom.xml
- rdbms-common/pom.xml
- rdbms-spring-boot-starter/pom.xml
- rdbms-support/pom.xml
- rest-common/pom.xml
- Uses new Maven 3.5+ conventions for modern CI friendly revisioning
- Updates Parent and Child POMs for modules to conform to revision
- See https://maven.apache.org/maven-ci-friendly.html#multi-module-setup
> Update POMs and add Snapshot workflow

- api-rest/src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBJsonFileCreateControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLJsonFileCreateControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mysql/MySQLJsonFileCreateControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/oracle/OracleJsonFileCreateControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/pg/PgInnerJoinControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/pg/PgInnerJoinMultiTableControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/pg/PgInnerSelfJoinControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/pg/PgJsonFileCreateControllerTest.java
> Fixes #787 make JSON File tests agnostic of FileSystem used

- pom.xml
This PR implements the following changes:
-  I have changed the springboot starter parent version to 3.3.5 in pom.xml
> updated the springboot version to 3.3.5 

- pg-dialect/src/main/java/com/homihq/db2rest/jdbc/config/driver/EnvVarSSLSocketFactory.java
Also declared explanatory variables to hopefully make it easier to read.
> Combine nested if-statements.

- api-rest/src/main/java/com/homihq/db2rest/interceptor/DatabaseContextRequestInterceptor.java
rename WHITE_LIST => whiteList so it lines up with Java variable standards
> rename WHITE_LIST to whiteList

- api-rest/src/test/java/com/homihq/db2rest/rest/mariadb/MariaDBRSqlOperatorReadControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mssql/MsSQLRSqlOperatorReadControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/mysql/MySQLRSqlOperatorReadControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/oracle/OracleRSqlOperatorReadControllerTest.java
- api-rest/src/test/java/com/homihq/db2rest/rest/pg/PgRSqlOperatorReadControllerTest.java
@kdhrubo : I don't have access to add reviewers — could you please add the appropriate reviewers and review as well Thanks!
> Support RsqlOperators integration test #338
